kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: justmiles
    password: 
      from_secret: DOCKER_TOKEN
    repo: justmiles/dev-sandbox
    tags: latest
    squash: true
    cache_from:
      - "justmiles/dev-sandbox:latest"