kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: justmiles
    password: 
      from_secret: DOCKER_TOKENgit 
    repo: justmiles/dev-sandbox
    tags: latest
    squash: true