kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  environment:
    DOCKER_API_VERSION: ${DOCKER_API_VERSION}
  settings:
    username: justmiles
    password: 
      from_secret: DOCKER_TOKEN
    repo: justmiles/dev-sandbox
    tags: latest
    squash: true
    cache_from:
      - "justmiles/dev-sandbox:latest"