kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: chrispruitt/dev-sandbox
    tags: latest
    squash: true
    auto_tag: true
    cache_from:
      - "chrispruitt/dev-sandbox:latest"
